name: Publish Image (fork)

on:
  push:
    branches: [fork]

jobs:
  build:
    name: Publish Image (fork)
    runs-on: ubuntu-latest
    concurrency: build-docker-images
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_ORG: jahands
      EARTHLY_SATELLITE: mini-sat
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1.0.11
        with:
          version: v0.8.6
      - uses: actions/checkout@v4
      - name: "Docker: Build"
        run: earthly --ci --push +docker
